version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.9"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt   # Sphinx + theme + myst only
    - method: pip
      path: .                               # install THIS repo into the RTD venv

# TEMP DIAGNOSTIC — keep for 1–2 builds, then remove
build:
  os: ubuntu-24.04
  tools: { python: "3.9" }
  jobs:
    post_install:
      - python -c "import sys; print('PYTHON:', sys.version)"
      - python -c "import GPmix, inspect, os; print('GPmix file:', GPmix.__file__)"
      - python -c "import importlib.metadata as m; print('GPmix pkg ver:', m.version('GPmix'))"