version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

sphinx:
  configuration: docs/source/conf.py  # adjust if your conf.py lives here

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .                   # installs GPmix into RTD's venv